# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twister',
            old_name='location',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='twister',
            old_name='marterial',
            new_name='content_id',
        ),
        migrations.RenameField(
            model_name='twister',
            old_name='name',
            new_name='difficulty',
        ),
        migrations.RemoveField(
            model_name='twister',
            name='value',
        ),
    ]
