# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20161031_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twister',
            name='content',
            field=models.CharField(max_length=999),
        ),
    ]
